version : "3.6"
services :
  postgres11.14:
    image : postgres:11.12-alpine
    environment :
      POSTGRES_DB: inliveroom
      POSTGRES_PASSWORD: inlive_room_pass
      POSTGRES_USER: inlive_room_user
      PGDATA: /data/posgres
    volumes : 
      - .docker/postgres-data:/data/posgres
    ports: 
      - "5432:5432"
    networks:
      - local
networks:
  local:
    driver: bridge
